<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:macro name="hc_sr04" params="name parent *origin">
		<link name="${prefix}_wheel">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>            
                <mass value="0.030"/>
                <inertia ixx="1.75e-5" ixy="0" ixz="0" iyy="1.75e-5" iyz="0" izz="1.75e-5"/>
            </inertial>

            <visual>
                <xacro:insert_block name="origin" />
                <geometry>
                    <cylinder radius="${wheel_radius}"  length="${wheel_width}"/>
                </geometry>
            </visual>

		</link> 
	</xacro:macro>


	<xacro:macro name="base_link" params="link_name body_height body_width body_length ">
        <link name="${link_name}">

            <visual>
                <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
                <geometry>
                    <box size="${body_length} ${body_width} ${body_height}"/>
                </geometry>
                <material name="Blue">
                    <color rgba="0 0.0 1.0 0.5"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
                <geometry>
                    <box size="${body_length} ${body_width} ${body_height}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 ${0.5*body_height}" rpy="0 0 0"/>
                <mass value="0.180"/>
                <inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>
            </inertial>

        </link>
	</xacro:macro>

</robot>
